### ISSUE TITLE
bug: `google_set_hostname` changes hostname after reboot

### ISSUE THREAD

**Issue by diamonwiggins** [GoogleCloudPlatform/guest-configs#69] opened 2024-03-11 23:54 UTC
Hello 👋 . I work for [Replicated](https://www.replicated.com/) where we maintain and support a `kubeadm` based Kubernetes installer, and we've noticed an issue recently where the hostname of a RHEL9 GCP instance changes during the DHCP lease renewal process(generally observed during reboot) which causes that node in the K8s cluster not to recover.

What we observe is the following:

1. New instance is created and the hostname is set to the fqdn of the instance name

`my-node.some.domain.internal`

2. Once the machine is rebooted or if you run a simple `dhclient -r && dhclient` to obtain a new lease, the script in `/usr/bin/google_set_hostname` is run which populates `/etc/host` with:

```bash
10.150.15.215 my-node.some.domain.internal my-node  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google
```

The interesting thing here is that in order for this code path to be hit, the following conditional must be true:

```bash
if [ -n "$new_host_name" ] && [ -n "$new_ip_address" ];
```

My best guest at the moment is that for a freshly created instance with default base images that this is always true or at least true the first time?

3. After `/etc/hosts` is updated, for systems that have Network Manager installed, the following command is run:

```bash
nmcli general hostname "${new_host_name%%.*}"
```

Before the `google_set_hostname` script is run, the hostname is the fqdn. Afterwards its just the short-hand name which in our case breaks anything that relies on the hostname not changing.

The feels like a bug to us. Any guidance is a appreciated. Thanks!

**Comment by a-crate** [comment] 2024-03-13 00:13
re point 1:
This generally happens because GCE vms receive the FQDN in the host name section of the DHCP response. The guest agent does not take over management of the primary NIC, so it's up to the OS networking stack whether they split that section or not.

re: point 2 and 3:
The final behavior is the intended behavior (hostname is the short-hand name, FQDN is in /etc/hosts). You are not seeing this until a reboot or a manual `dhclient` invocation though?

You're right (in the other bug) that the functionality for this is moving to guest-agent in the future but it's here now so we'll keep the discussion here.

**Comment by a-crate** [comment] 2024-04-25 22:41
Our hostname setup script is not executing correctly on latest versions of RHEL 9. #70 is the fix.

**Closed** 2024-05-01 18:59 UTC

**Comment by a-crate** [comment] 2024-05-01 19:16
I'll ping here again when we cut a release with that PR.
